# Bernoulli Naive Bayes

In [1]:
import numpy as np

In [2]:
X = []
y = []


X = X + 10*[[0, 0]]
y = y + 10*[0]

X = X + 20*[[0, 0]]
y = y + 20*[1]


X = X + 30*[[0, 1]]
y = y + 30*[0]

X = X + 40*[[0, 1]]
y = y + 40*[1]

X = X + 50*[[1, 0]]
y = y + 50*[0]

X = X + 60*[[1, 0]]
y = y + 60*[1]

X = X + 70*[[1, 1]]
y = y + 70*[0]

X = X + 80*[[1, 1]]
y = y + 80*[1]

X = np.asarray(X)
y = np.asarray(y)

In [3]:
nf = X.shape[1]
classes = np.unique(y)

print("Class")
print("Y \t Count")
for yv in classes:
    c = np.sum(y == yv)
    print("%d \t %d" %(yv, c))

for f in range(nf):
    print("\nFeature", f)
    print("F \t Y \t Count")
    for xv in range(2):
        for yv in classes:
            c = np.sum(X[y == yv][:, f] == xv)
            print("%d \t %d \t %d" %(xv, yv, c))





Class
Y 	 Count
0 	 160
1 	 200

Feature 0
F 	 Y 	 Count
0 	 0 	 40
0 	 1 	 60
1 	 0 	 120
1 	 1 	 140

Feature 1
F 	 Y 	 Count
0 	 0 	 60
0 	 1 	 80
1 	 0 	 100
1 	 1 	 120


In [4]:
a=(160/360)*(40/160)*(60/160)
b=(200/360)*(60/200)*(80/200)

In [5]:
a/(a+b)

0.3846153846153846

In [6]:
10/30

0.3333333333333333

In [7]:
from sklearn.naive_bayes import BernoulliNB

In [8]:
alpha = 1e-10

In [9]:
clf = BernoulliNB(alpha=alpha, fit_prior=True)

In [10]:
clf.fit(X, y)

BernoulliNB(alpha=1e-10, binarize=0.0, class_prior=None, fit_prior=True)

In [11]:
clf.classes_

array([0, 1])

In [12]:
clf.class_count_

array([160., 200.])

In [13]:
np.log(160/360)

-0.8109302162163288

In [14]:
np.log(200/360)

-0.587786664902119

In [15]:
clf.class_log_prior_

array([-0.81093022, -0.58778666])

In [16]:
np.exp(clf.class_log_prior_)

array([0.44444444, 0.55555556])

In [17]:
clf.class_count_[0] / clf.class_count_.sum()

0.4444444444444444

As you can see, the scikit-learn does not smooth the class prior with alpha.

In [18]:
clf.feature_count_

array([[120., 100.],
       [140., 120.]])

Keeps track of #(Feature = True | Y). Rows are classes, columns are features.

In [19]:
clf.feature_log_prob_

array([[-0.28768207, -0.47000363],
       [-0.35667494, -0.51082562]])

In [20]:
np.exp(clf.feature_log_prob_)

array([[0.75 , 0.625],
       [0.7  , 0.6  ]])

In [21]:
(120 + alpha) / (160 + 2*alpha)

0.7499999999996875

In [22]:
(100 + alpha) / (160 + 2*alpha)

0.6249999999998438

In [23]:
(140 + alpha) / (200 + 2*alpha)

0.6999999999997999

In [24]:
(120 + alpha) / (200 + 2*alpha)

0.5999999999999

In [25]:
(clf.feature_count_ + alpha) / (clf.class_count_ + 2*alpha).reshape(-1, 1)

array([[0.75 , 0.625],
       [0.7  , 0.6  ]])

In [26]:
1 - np.exp(clf.feature_log_prob_)

array([[0.25 , 0.375],
       [0.3  , 0.4  ]])

In [27]:
(40 + alpha) / (160 + 2*alpha)

0.25000000000031253

In [28]:
(60 + alpha) / (160 + 2*alpha)

0.37500000000015626

In [29]:
(60 + alpha) / (200 + 2*alpha)

0.3000000000002

In [30]:
(80 + alpha) / (200 + 2*alpha)

0.4000000000001

In [31]:
clf.feature_log_prob_

array([[-0.28768207, -0.47000363],
       [-0.35667494, -0.51082562]])

In [32]:
false_feature_log_prob = np.log(1 - np.exp(clf.feature_log_prob_))
false_feature_log_prob

array([[-1.38629436, -0.98082925],
       [-1.2039728 , -0.91629073]])

In [33]:
clf.class_log_prior_

array([-0.81093022, -0.58778666])

In [34]:
x = np.asarray([[0, 0]])

In [35]:
jll = clf._joint_log_likelihood([[0, 0]])
jll

array([[-3.17805383, -2.7080502 ]])

In [36]:
false_feature_log_prob[:, 0] + false_feature_log_prob[:, 1] + clf.class_log_prior_

array([-3.17805383, -2.7080502 ])

In [37]:
np.exp(jll) / np.sum(np.exp(jll))

array([[0.38461538, 0.61538462]])

In [38]:
clf.predict_proba([[0, 0]])

array([[0.38461538, 0.61538462]])

In [39]:
clf.predict_log_proba([[0, 0]])

array([[-0.95551145, -0.48550782]])

In [40]:
from scipy.special import logsumexp

In [41]:
np.log(np.sum(np.exp(jll)))

-2.222542385319304

In [42]:
logsumexp(jll)

-2.2225423853193043

In [43]:
jll - logsumexp(jll)

array([[-0.95551145, -0.48550782]])

In [44]:
np.exp(jll - logsumexp(jll))

array([[0.38461538, 0.61538462]])

In [45]:
jll2 = np.asarray([-1000, -1003])

In [46]:
np.log(np.sum(np.exp(jll2)))

c:\users\mbilg\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [47]:
logsumexp(jll2)

-999.9514126484263

In [48]:
np.exp(jll2 - logsumexp(jll2))

array([0.95257413, 0.04742587])

In [49]:
np.exp(0)/(np.exp(0) + np.exp(-3))

0.9525741268224334

In [50]:
fw = false_feature_log_prob[0] - false_feature_log_prob[1]
fw

array([-0.18232156, -0.06453852])

In [51]:
tw = clf.feature_log_prob_[0] - clf.feature_log_prob_[1]
tw

array([0.06899287, 0.04082199])

In [52]:
b = clf.class_log_prior_[0] - clf.class_log_prior_[1]
b

-0.2231435513142097

In [53]:
lr = b + fw[0] + fw[1]
lr

-0.4700036292449815

In [54]:
np.exp(lr) / (1+np.exp(lr))

0.3846153846155631

In [55]:
clf.predict_proba([[0, 0]])

array([[0.38461538, 0.61538462]])

Illustration of product of small numbers vs sum of log of small numbers

In [56]:
np.random.seed(0)

In [57]:
p = np.random.random(1000)

In [58]:
p = np.clip(p, 0.001, 1)

In [59]:
np.min(p)

0.001

In [60]:
np.max(p)

0.9998085781169653

In [61]:
np.product(p)

0.0

In [62]:
np.sum(np.log(p))

-1004.4728783308233

In [63]:
np.exp(-1004.47)

0.0