# Multinomial Naive Bayes

In [1]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB, MultinomialNB

In [2]:
X = []
y = []


X = X + 56*[[0, 0]]
y = y + 56*[0]

X = X + 81*[[0, 0]]
y = y + 81*[1]


X = X + 24*[[0, 1]]
y = y + 24*[0]

X = X + 459*[[0, 1]]
y = y + 459*[1]

X = X + 224*[[1, 0]]
y = y + 224*[0]

X = X + 9*[[1, 0]]
y = y + 9*[1]

X = X + 96*[[1, 1]]
y = y + 96*[0]

X = X + 51*[[1, 1]]
y = y + 51*[1]

X = np.asarray(X)
y = np.asarray(y)

In [3]:
nf = X.shape[1]
classes = np.unique(y)

print("Class")
print("Y \t Count")
for yv in classes:
    c = np.sum(y == yv)
    print("%d \t %d" %(yv, c))

for f in range(nf):
    print("\nFeature", f)
    print("F \t Y \t Count")
    for xv in range(2):
        for yv in classes:
            c = np.sum(X[y == yv][:, f] == xv)
            print("%d \t %d \t %d" %(xv, yv, c))





Class
Y 	 Count
0 	 400
1 	 600

Feature 0
F 	 Y 	 Count
0 	 0 	 80
0 	 1 	 540
1 	 0 	 320
1 	 1 	 60

Feature 1
F 	 Y 	 Count
0 	 0 	 280
0 	 1 	 90
1 	 0 	 120
1 	 1 	 510


In [4]:
alpha = 1e-10

In [5]:
b_clf = BernoulliNB(alpha=alpha, fit_prior=True)
m_clf = MultinomialNB(alpha=alpha, fit_prior=True)

In [6]:
b_clf.fit(X, y)
m_clf.fit(X, y)

MultinomialNB(alpha=1e-10, class_prior=None, fit_prior=True)

In [7]:
print(np.exp(b_clf.class_log_prior_))
print()
print(np.exp(m_clf.class_log_prior_))

[0.4 0.6]

[0.4 0.6]


In [8]:
print(b_clf.feature_count_)
print()
print(m_clf.feature_count_)

[[320. 120.]
 [ 60. 510.]]

[[320. 120.]
 [ 60. 510.]]


In [9]:
print(np.exp(b_clf.feature_log_prob_))
print()
print(np.exp(m_clf.feature_log_prob_))

[[0.8  0.3 ]
 [0.1  0.85]]

[[0.72727273 0.27272727]
 [0.10526316 0.89473684]]


In [10]:
320/(320+120)

0.7272727272727273

In [11]:
60/(60+510)

0.10526315789473684

In [12]:
a = 0.4*0.2*0.7
b = 0.6*0.9*0.15
a/(a+b)

0.40875912408759124

In [13]:
x = np.asarray([[0, 0]])

print(b_clf.predict_proba(x))
print()
print(m_clf.predict_proba(x))

[[0.40875912 0.59124088]]

[[0.4 0.6]]


In [14]:
tw = b_clf.feature_log_prob_[1] - b_clf.feature_log_prob_[0]
tw

array([-2.07944154,  1.04145387])

In [15]:
flp = np.log(1-np.exp(b_clf.feature_log_prob_))
fw = flp[1] - flp[0]
fw

array([ 1.5040774 , -1.54044504])

In [16]:
mw = m_clf.feature_log_prob_[1] - m_clf.feature_log_prob_[0]
mw

array([-1.93283807,  1.18805735])

In [17]:
x = np.asarray([[0, 1]])

print(b_clf.predict_proba(x))
print()
print(m_clf.predict_proba(x))

[[0.04968944 0.95031056]]

[[0.16888889 0.83111111]]


In [18]:
x = np.asarray([[1, 0]])

print(b_clf.predict_proba(x))
print()
print(m_clf.predict_proba(x))

[[0.96137339 0.03862661]]

[[0.82162162 0.17837838]]


In [19]:
x = np.asarray([[1, 1]])

print(b_clf.predict_proba(x))
print()
print(m_clf.predict_proba(x))

[[0.65306122 0.34693878]]

[[0.58402427 0.41597573]]
